[Data_Params]
types = "UTS"
# datasets = ["AIOPS", "NAB", "WSD", "Yahoo"]
datasets = ["NAB", "WSD", "Yahoo"]
train_proportion = 1
valid_proportion = 0
preprocess = "min_max"

[Analysis]
 plot_score = true
 plot_y_hat = false

[Model_Params.Default]
 cuda = true
 win_size = 128
 lr = 1e-6
 epochs = 100
 batch_size = 64
 num = 10
 step = 64