[Data_Params]
types = "UTS"
datasets = ["AIOPS", "NAB", "WSD", "Yahoo"]
train_proportion = 1
valid_proportion = 0.2
preprocess = "z-score"

[Analysis]
 plot_score = true
 plot_y_hat = false

# if your want to specify the model params for one Dataset
[Model_Params.Default]
 cuda = true
 win_size = 100
 input_c = 1
 output_c = 1
 earlystop_patience = 7
 num_epochs = 10
 learning_rate = 1e-4
 batch_size = 256
 step = 1
 k = 3